class Cereals {
	 public static void main(String Args[]){
		 String cereal1="Wheat";
		 String cereal2="Rice";
		 String cereal3="Maize";
		 String cereal4="Barley";
		 String cereal5="Oats";
		 String cereal6="Rye";
		 String cereal7="Sorghum";
		 String cereal8="Millet";
		 String cereal9="Quinoa";
		 String cereal10="Buckwheat";
		 String cereal11="Fonio";
		 String cereal12="Teff";
		 String cereal13="Spelt";
		 String cereal14="Triticale";
		 String cereal15="Amaranth";
		 String cereal16="Kamut";
		 String cereal17="Farro";
		 String cereal18="Freekeh";
		 String cereal19="Emmer";
		 String cereal20="Einkorn";
		 String cereal21="Wild Rice";
		 String cereal22="Job's Tears";
		 String cereal23="Canary Seed";
		 String cereal24="Fonio";
		 String cereal25="Chia";
		 String cereal26="Broomcorn";
		 String cereal27="Finger Millet";
		 String cereal28="Pearl Millet";
		 String cereal29="Little Millet";
		 String cereal30="Proso Millet";
		 
		 String[] cereals={cereal1,cereal2,cereal3,cereal4,cereal5,cereal6,cereal7,cereal8,cereal9,cereal10,cereal11,cereal12,cereal13,cereal14,cereal15,cereal16,cereal17,cereal18,cereal19,cereal20,cereal21,cereal22,cereal23,cereal24,cereal25,cereal26,cereal27,cereal28,cereal29,cereal30, "hiiiiiiiidgdsh"};
		
		 System.out.println("Updated cereals");
 		 System.out.println("First cereal is : "+cereals[0]);
		 System.out.println("Second cereal is : "+cereals[1]);
		 System.out.println("Third cereal is : "+cereals[2]);
		 System.out.println("Forth cereal is : "+cereals[3]);
		 System.out.println("Fifth cereal is : "+cereals[4]);
		 System.out.println("Sixth cereal is : "+cereals[5]);
		 System.out.println("Seventh cereal is : "+cereals[6]);
		 System.out.println("Eighth cereal is : "+cereals[7]);
		 System.out.println("Ninth cereal is : "+cereals[8]);
		 System.out.println("Tenth cereal is : "+cereals[9]);
		 System.out.println("Eleventh cereal is : "+cereals[10]);
		 System.out.println("Twelth cereal is : "+cereals[11]);
		 System.out.println("13th cereal is : "+cereals[12]);
		 System.out.println("14th cereal is : "+cereals[13]);
		 System.out.println("15th cereal is : "+cereals[14]);
		 System.out.println("16th cereal is : "+cereals[15]);
		 System.out.println("17th cereal is : "+cereals[16]);
		 System.out.println("18th cereal is : "+cereals[17]);
		 System.out.println("19th cereal is : "+cereals[18]);
		 System.out.println("20th cereal is : "+cereals[19]);
		 System.out.println("21st cereal is : "+cereals[20]);
		 System.out.println("22nd cereal is : "+cereals[21]);
		 System.out.println("23rd cereal is : "+cereals[22]);
		 System.out.println("24th cereal is : "+cereals[23]);
		 System.out.println("25th cereal is : "+cereals[24]);
		 System.out.println("26th cereal is : "+cereals[25]);
		 System.out.println("27th cereal is : "+cereals[26]);
		 System.out.println("28th cereal is : "+cereals[27]);
		 System.out.println("29th cereal is : "+cereals[28]);
		 System.out.println("30th cereal is : "+cereals[29]);
		 System.out.println("31st cereal is : "+cereals[30]);
		 
		 cereals[0]="Fonio";
		 cereals[1]="Barley";
		 cereals[2]="Buckwheat";
		 cereals[13]="Little Millet";
		 cereals[16]="Pearl Millet";
		 cereals[17]="Finger Millet";
		 cereals[18]="Chia";
		 cereals[21]="Teff";
		 cereals[24]="Amaranth";
		 cereals[29]="Proso Millet";
		 System.out.println("\n\nUpdated cereals names : ");
		 System.out.println("First cereal is : "+cereals[0]);
		 System.out.println("Second cereal is : "+cereals[1]);
		 System.out.println("Third cereal is : "+cereals[2]);
		 System.out.println("Forth cereal is : "+cereals[3]);
		 System.out.println("Fifth cereal is : "+cereals[4]);
		 System.out.println("Sixth cereal is : "+cereals[5]);
		 System.out.println("Seventh cereal is : "+cereals[6]);
		 System.out.println("Eighth cereal is : "+cereals[7]);
		 System.out.println("Ninth cereal is : "+cereals[8]);
		 System.out.println("Tenth cereal is : "+cereals[9]);
		 System.out.println("Eleventh cereal is : "+cereals[10]);
		 System.out.println("Twelth cereal is : "+cereals[11]);
		 System.out.println("13th cereal is : "+cereals[12]);
		 System.out.println("14th cereal is : "+cereals[13]);
		 System.out.println("15th cereal is : "+cereals[14]);
		 System.out.println("16th cereal is : "+cereals[15]);
		 System.out.println("17th cereal is : "+cereals[16]);
		 System.out.println("18th cereal is : "+cereals[17]);
		 System.out.println("19th cereal is : "+cereals[18]);
		 System.out.println("20th cereal is : "+cereals[19]);
		 System.out.println("21st cereal is : "+cereals[20]);
		 System.out.println("22nd cereal is : "+cereals[21]);
		 System.out.println("23rd cereal is : "+cereals[22]);
		 System.out.println("24th cereal is : "+cereals[23]);
		 System.out.println("25th cereal is : "+cereals[24]);
		 System.out.println("26th cereal is : "+cereals[25]);
		 System.out.println("27th cereal is : "+cereals[26]);
		 System.out.println("28th cereal is : "+cereals[27]);
		 System.out.println("29th cereal is : "+cereals[28]);
		 System.out.println("30th cereal is : "+cereals[29]);
	 }
 }
