class Cloth{
	 public static void main(String Args[]){
		 String cloth1="Shirt";
		 String cloth2="Pant";
		 String cloth3="T-shirt";
		 String cloth4="Jeans";
		 String cloth5="Hoodie";
		 String cloth6="Jacket";
		 String cloth7="Sweater";
		 String cloth8="Blazer";
		 String cloth9="Coat";
		 String cloth10="Vest";
		 String cloth11="Kurta";
		 String cloth12="Leggings";
		 String cloth13="Skirt";
		 String cloth14="Shorts";
		 String cloth15="Jumpsuit";
		 String cloth16="Saree";
		 String cloth17="Dress";
		 String cloth18="Tunic";
		 String cloth19="Polo shirt";
		 String cloth20="Cargo pants";
		 String cloth21="Chinos";
		 String cloth22="Tracksuit";
		 String cloth23="Sweatshirt";
		 String cloth24="Overcoat";
		 String cloth25="Cardigan";
		 String cloth26="Tank top";
		 String cloth27="Camisole";
		 String cloth28="Crop top";
		 String cloth29="Palazzo pants";
		 String cloth30="Joggers";
		 
		 String[] cloths={cloth1,cloth2,cloth3,cloth4,cloth5,cloth6,cloth7,cloth8,cloth9,cloth10,cloth11,cloth12,cloth13,cloth14,cloth15,cloth16,cloth17,cloth18,cloth19,cloth20,cloth21,cloth22,cloth23,cloth24,cloth25,cloth26,cloth27,cloth28,cloth29,cloth30};
		 System.out.println("First cloth is : "+cloths[0]);
		 System.out.println("Second cloth is : "+cloths[1]);
		 System.out.println("Third cloth is : "+cloths[2]);
		 System.out.println("Forth cloth is : "+cloths[3]);
		 System.out.println("Fifth cloth is : "+cloths[4]);
		 System.out.println("Sixth cloth is : "+cloths[5]);
		 System.out.println("Seventh cloth is : "+cloths[6]);
		 System.out.println("Eighth cloth is : "+cloths[7]);
		 System.out.println("Ninth cloth is : "+cloths[8]);
		 System.out.println("Tenth cloth is : "+cloths[9]);
		 System.out.println("Eleventh cloth is : "+cloths[10]);
		 System.out.println("Twelth cloth is : "+cloths[11]);
		 System.out.println("13th cloth is : "+cloths[12]);
		 System.out.println("14th cloth is : "+cloths[13]);
		 System.out.println("15th cloth is : "+cloths[14]);
		 System.out.println("16th cloth is : "+cloths[15]);
		 System.out.println("17th cloth is : "+cloths[16]);
		 System.out.println("18th cloth is : "+cloths[17]);
		 System.out.println("19th cloth is : "+cloths[18]);
		 System.out.println("20th cloth is : "+cloths[19]);
		 System.out.println("21st cloth is : "+cloths[20]);
		 System.out.println("22nd cloth is : "+cloths[21]);
		 System.out.println("23rd cloth is : "+cloths[22]);
		 System.out.println("24th cloth is : "+cloths[23]);
		 System.out.println("25th cloth is : "+cloths[24]);
		 System.out.println("26th cloth is : "+cloths[25]);
		 System.out.println("27th cloth is : "+cloths[26]);
		 System.out.println("28th cloth is : "+cloths[27]);
		 System.out.println("29th cloth is : "+cloths[28]);
		 System.out.println("30th cloth is : "+cloths[29]);
		 
		 cloths[0]="Dungarees";
		 cloths[1]="Anarkali suit";
		 cloths[2]="Sherwani";
		 cloths[13]="Salwar kameez";
		 cloths[16]="Dhoti";
		 cloths[17]="Lehenga";
		 cloths[18]="Parka";
		 cloths[21]="Poncho";
		 cloths[24]="Kimono";
		 cloths[29]="Trench coat";
		 System.out.println("First cloth is : "+cloths[0]);
		 System.out.println("Second cloth is : "+cloths[1]);
		 System.out.println("Third cloth is : "+cloths[2]);
		 System.out.println("Forth cloth is : "+cloths[3]);
		 System.out.println("Fifth cloth is : "+cloths[4]);
		 System.out.println("Sixth cloth is : "+cloths[5]);
		 System.out.println("Seventh cloth is : "+cloths[6]);
		 System.out.println("Eighth cloth is : "+cloths[7]);
		 System.out.println("Ninth cloth is : "+cloths[8]);
		 System.out.println("Tenth cloth is : "+cloths[9]);
		 System.out.println("Eleventh cloth is : "+cloths[10]);
		 System.out.println("Twelth cloth is : "+cloths[11]);
		 System.out.println("13th cloth is : "+cloths[12]);
		 System.out.println("14th cloth is : "+cloths[13]);
		 System.out.println("15th cloth is : "+cloths[14]);
		 System.out.println("16th cloth is : "+cloths[15]);
		 System.out.println("17th cloth is : "+cloths[16]);
		 System.out.println("18th cloth is : "+cloths[17]);
		 System.out.println("19th cloth is : "+cloths[18]);
		 System.out.println("20th cloth is : "+cloths[19]);
		 System.out.println("21st cloth is : "+cloths[20]);
		 System.out.println("22nd cloth is : "+cloths[21]);
		 System.out.println("23rd cloth is : "+cloths[22]);
		 System.out.println("24th cloth is : "+cloths[23]);
		 System.out.println("25th cloth is : "+cloths[24]);
		 System.out.println("26th cloth is : "+cloths[25]);
		 System.out.println("27th cloth is : "+cloths[26]);
		 System.out.println("28th cloth is : "+cloths[27]);
		 System.out.println("29th cloth is : "+cloths[28]);
		 System.out.println("30th cloth is : "+cloths[29]);
	 }
 }