class CountryRunner {
    public static void main(String[] args) {
        
		
		Country.countryInfo("Albania");
        Country.countryInfo("Algeria");
        Country.countryInfo("Angola");
        Country.countryInfo("Andorra");
        Country.countryInfo("Antigua and Barbuda");
        Country.countryInfo("Argentina");
        Country.countryInfo("Armenia");
        Country.countryInfo("Australia");
        Country.countryInfo("Austria");
        Country.countryInfo("Azerbaijan");
        Country.countryInfo("Bahamas");
        Country.countryInfo("Bahrain");
        Country.countryInfo("Bangladesh");
        Country.countryInfo("Barbados");
        Country.countryInfo("Belarus");
        Country.countryInfo("Belgium");
        Country.countryInfo("Belize");
        Country.countryInfo("Benin");
        Country.countryInfo("Bhutan");
        Country.countryInfo("Bolivia");
		Country.countryInfo("Bosnia and Herzegovina");
        Country.countryInfo("Botswana");
        Country.countryInfo("Brazil");
        Country.countryInfo("Brunei");
        Country.countryInfo("Bulgaria");
        Country.countryInfo("Burkina Faso");
        Country.countryInfo("Burundi");
        Country.countryInfo("Cambodia");
        Country.countryInfo("Cameroon");
        Country.countryInfo("Canada");
        Country.countryInfo("Central African Republic");
        Country.countryInfo("Chad");
        Country.countryInfo("Chile");
        Country.countryInfo("China");
        Country.countryInfo("Colombia");
        Country.countryInfo("Comoros");
        Country.countryInfo("Congo (Democratic Republic)");
        Country.countryInfo("Congo (Republic)");
        Country.countryInfo("Costa Rica");
        Country.countryInfo("Croatia");
		Country.countryInfo("Cuba");
        Country.countryInfo("Cyprus");
        Country.countryInfo("Denmark");
        Country.countryInfo("Czechia (Czech Republic)");
        Country.countryInfo("Djibouti");
        Country.countryInfo("Dominica");
        Country.countryInfo("Dominican Republic");
        Country.countryInfo("Egypt");
        Country.countryInfo("El Salvador");
        Country.countryInfo("Equatorial Guinea");
        Country.countryInfo("Eritrea");
		Country.countryInfo("Ecuador");
        Country.countryInfo("Estonia");
        Country.countryInfo("Eswatini (Swaziland)");
        Country.countryInfo("Ethiopia");
        Country.countryInfo("Fiji");
        Country.countryInfo("Finland");
        Country.countryInfo("France");
        Country.countryInfo("Gabon");
        Country.countryInfo("Gambia");
        Country.countryInfo("Georgia");
		Country.countryInfo("Germany");
        Country.countryInfo("Ghana");
        Country.countryInfo("Greece");
        Country.countryInfo("Grenada");
        Country.countryInfo("Guatemala");
        Country.countryInfo("Guinea");
        Country.countryInfo("Guinea-Bissau");
        Country.countryInfo("Guyana");
        Country.countryInfo("Haiti");
        Country.countryInfo("Honduras");
        Country.countryInfo("Hungary");
        Country.countryInfo("Iceland");
        Country.countryInfo("India");
        Country.countryInfo("Indonesia");
        Country.countryInfo("Iran");
        Country.countryInfo("Iraq");
        Country.countryInfo("Ireland");
        Country.countryInfo("Israel");
        Country.countryInfo("Italy");
        Country.countryInfo("Jamaica");
		Country.countryInfo("Cabo Verde"); //
		Country.countryInfo("Japan");
        Country.countryInfo("Jordan");
        Country.countryInfo("Kazakhstan");
        Country.countryInfo("Kenya");
        Country.countryInfo("Kiribati");
        Country.countryInfo("Korea (North)");
        Country.countryInfo("Korea (South)");
        Country.countryInfo("Kuwait");
        Country.countryInfo("Kyrgyzstan");
        Country.countryInfo("Laos");
        Country.countryInfo("Latvia");
        Country.countryInfo("Lebanon");
        Country.countryInfo("Lesotho");
        Country.countryInfo("Liberia");
        Country.countryInfo("Libya");
        Country.countryInfo("Liechtenstein");
        Country.countryInfo("Lithuania");
		Country.countryInfo("Luxembourg");
		Country.countryInfo("Madagascar");
		Country.countryInfo("Malawi");
		Country.countryInfo("Malaysia");
		Country.countryInfo("Maldives");
		Country.countryInfo("Mali");
		Country.countryInfo("Malta");
		Country.countryInfo("Marshall Islands");
		Country.countryInfo("Mauritania");
		Country.countryInfo("Mauritius");
		Country.countryInfo("Mexico");
		Country.countryInfo("Micronesia");
		Country.countryInfo("Moldova");
		Country.countryInfo("Monaco");
		Country.countryInfo("Mongolia");
		Country.countryInfo("Montenegro");
		Country.countryInfo("Morocco");
		Country.countryInfo("Mozambique");
		Country.countryInfo("Myanmar (Burma)");
		Country.countryInfo("Namibia");
		Country.countryInfo("Nauru");
		Country.countryInfo("Nepal");
		Country.countryInfo("Netherlands");
		Country.countryInfo("New Zealand");
		Country.countryInfo("Nicaragua");
		Country.countryInfo("Niger");
		Country.countryInfo("Nigeria");
		Country.countryInfo("North Macedonia");
		Country.countryInfo("Norway");
		Country.countryInfo("Oman");
		Country.countryInfo("Pakistan");
		Country.countryInfo("Palau");
		Country.countryInfo("Panama");
		Country.countryInfo("Papua New Guinea");
		Country.countryInfo("Paraguay");
		Country.countryInfo("Peru");
		Country.countryInfo("Philippines");
		Country.countryInfo("Poland");
		Country.countryInfo("Portugal");
		Country.countryInfo("Qatar");
		Country.countryInfo("Romania");
		Country.countryInfo("Russia");
		Country.countryInfo("Rwanda");
		Country.countryInfo("Saint Kitts and Nevis");
		Country.countryInfo("Saint Lucia");
		Country.countryInfo("Saint Vincent and the Grenadines");
		Country.countryInfo("Samoa");
		Country.countryInfo("San Marino");
		Country.countryInfo("Sao Tome and Principe");
		Country.countryInfo("Saudi Arabia");
		Country.countryInfo("Senegal");
		Country.countryInfo("Serbia");
		Country.countryInfo("Seychelles");
		Country.countryInfo("Sierra Leone");
		Country.countryInfo("Singapore");
		Country.countryInfo("Slovakia");
		Country.countryInfo("Slovenia");
		Country.countryInfo("Solomon Islands");
		Country.countryInfo("Somalia");
		Country.countryInfo("South Africa");
		Country.countryInfo("South Sudan");
		Country.countryInfo("Spain");
		Country.countryInfo("Sri Lanka");
		Country.countryInfo("Sudan");
		Country.countryInfo("Suriname");
		Country.countryInfo("Sweden"); 
		Country.countryInfo("Switzerland");
		Country.countryInfo("Syria");
		Country.countryInfo("Taiwan");
		Country.countryInfo("Tajikistan");
		Country.countryInfo("Tanzania");
		Country.countryInfo("Thailand");
		Country.countryInfo("Timor-Leste");
		Country.countryInfo("Togo");
		Country.countryInfo("Tonga");
		Country.countryInfo("Trinidad and Tobago");
		Country.countryInfo("Tunisia");
		Country.countryInfo("Turkey");
		Country.countryInfo("Turkmenistan");
		Country.countryInfo("Tuvalu");
		Country.countryInfo("Uganda");
		Country.countryInfo("Ukraine");
		Country.countryInfo("United Arab Emirates");
		Country.countryInfo("United Kingdom");
		Country.countryInfo("United States");
		Country.countryInfo("Uruguay");
		Country.countryInfo("Uzbekistan");
		Country.countryInfo("Vanuatu");
		Country.countryInfo("Vatican City (Holy See)");
		Country.countryInfo("Venezuela");
		Country.countryInfo("Vietnam");
		Country.countryInfo("Yemen");
		Country.countryInfo("Zambia");
		Country.countryInfo("Zimbabwe");
		Country.countryInfo("New York");
		Country.countryInfo("Asia");
		

    }
}
